name: deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: [self-hosted, Linux]

    steps:

      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Update version
        run: >-
          mvn versions:set
          -DnewVersion=${RELEASE_VERSION} -DoldVersion=*
          -DgroupId=* -DartifactId=*
          --batch-mode --no-transfer-progress -Dsilent=true

      - name: Deploy artifact
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER}}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: >-
          mvn --settings .github/workflows/settings.xml
          -pl "!:hiit-ms-common-springboot, !:ms-dummy-service"
          deploy
          --batch-mode --no-transfer-progress -Dsilent=true

