name: deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Update version
        run: >-
          mvn versions:set
          -DnewVersion=${RELEASE_VERSION} -DoldVersion=*
          -DgroupId=* -DartifactId=*
          --batch-mode --no-transfer-progress -Dsilent=true

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }}
